# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build daily plots

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 20 * * *


jobs:
  build-daily-plots:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy pandas
    - name: Build italian plots
      run: |
        python plotItalianBreakdown.py
    - name: Build province plots
      run: |
        python plotProvinceData.py
    - name: Build regional plots
      run: |
        python plotRegionBreakdown.py
    
    - name: Upload plots to Wiki
      uses: docker://decathlon/wiki-page-creator-action:2.0.1
      env:
        GH_PAT: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        ACTION_MAIL: smnbologna@gmail.com
        ACTION_NAME: simonecid
        OWNER: simonecid
        REPO_NAME: COVID19_Analysis
        MD_FOLDER: plots

