# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build daily plots

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 00 * * * *


jobs:
  build-daily-plots:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy pandas
    - name: Build italian plots
      run: |
        python plotItalianBreakdown.py
    - name: Build italian province plots
      run: |
        python plotProvinceData.py
    - name: Build italian regional plots
      run: |
        python plotRegionBreakdown.py
    - name: Build country breakdown plots
      run: |
        python plotCountryBreakdown.py
    - name: Build country comparison plots
      run: |
        python plotCountryComparison.py
    - name: Build daily breakdowns
      run: |
        python plotCountryIncreaseBreakdown.py
    - name: Run SIR fits
      run: |
        python fitNationalSIR.py
    
    - name: Commit files
      run: |
        number=`git status -s plots | wc -l`
        if [ $number != 0 ] ; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f plots/*.png
          git commit -m "Add changes"
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

